from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_report(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build_markdown(report: dict) -> str:
    repo_url = report.get("repo_url", "")
    score = report.get("score_total", 0)
    stacks = report.get("detected_stacks", [])
    metrics = report.get("project_metrics", {}) if isinstance(report.get("project_metrics"), dict) else {}
    categories = report.get("categories", [])
    fix_plan = report.get("fix_plan", [])

    lines = [
        "## Repo Inspector",
        "",
        f"- Repository: `{repo_url}`",
        f"- Total score: **{score}/100**",
        f"- Detected stacks: `{', '.join(stacks) if stacks else 'n/a'}`",
        f"- Code lines: **{metrics.get('total_code_lines', 0)}**",
        (
            f"- Code files: **{metrics.get('total_code_files', 0)}** "
            f"(scanned {metrics.get('scanned_code_files', 0)})"
        ),
        "",
        "### Category scores",
    ]
    for category in categories:
        name = category.get("name", "Unknown")
        category_score = category.get("score", 0)
        category_weight = category.get("weight", 0)
        lines.append(f"- `{name}`: **{category_score}/{category_weight}**")

    if fix_plan:
        lines.extend(["", "### Top fixes", ""])
        for item in fix_plan[:5]:
            lines.append(
                f"{item.get('priority', '?')}. **{item.get('check_name', 'check')}** "
                f"(impact +{item.get('impact_points', 0)}): {item.get('action', '')}"
            )
    lines.append("")
    lines.append("_Generated by Repo Inspector workflow._")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Render markdown summary from report JSON.")
    parser.add_argument("--report-file", required=True, help="Path to report JSON file")
    parser.add_argument("--output-file", required=True, help="Path to markdown output")
    args = parser.parse_args()

    report_path = Path(args.report_file)
    output_path = Path(args.output_file)
    report = load_report(report_path)
    markdown = build_markdown(report)
    output_path.write_text(markdown, encoding="utf-8")
    print(f"Summary written: {output_path.as_posix()}")


if __name__ == "__main__":
    main()

