const I18N = {
  en: {
    title: "Repo Inspector (Pages)",
    subtitle: "Static mode: reports are generated by GitHub Actions.",
    repoLabel: "GitHub repository URL",
    loadBtn: "Load report",
    noReport: "Report not found yet.",
    reportReady: "Report loaded.",
    invalidUrl: "Invalid GitHub URL.",
    totalScore: "Total score",
    codeLines: "Code lines",
    codeFiles: "Code files",
    recommendations: "Recommendations",
    howToGenerate:
      "Generate a report using the GitHub Actions workflow `generate-report.yml`, then reload this page.",
    openActions: "Open Actions workflow",
    localCommand: "Or generate locally:",
    tabDefault: "Repo Inspector · Static Reports",
    tabLoaded: "Repo Inspector · {repo} · {score}/100",
  },
  ru: {
    title: "Repo Inspector (Pages)",
    subtitle: "Статический режим: отчеты генерируются через GitHub Actions.",
    repoLabel: "Ссылка на GitHub-репозиторий",
    loadBtn: "Загрузить отчет",
    noReport: "Отчет пока не найден.",
    reportReady: "Отчет успешно загружен.",
    invalidUrl: "Некорректная ссылка на GitHub-репозиторий.",
    totalScore: "Итоговый score",
    codeLines: "Строки кода",
    codeFiles: "Файлы кода",
    recommendations: "Рекомендации",
    howToGenerate:
      "Сгенерируйте отчет через workflow `generate-report.yml` в GitHub Actions, затем обновите страницу.",
    openActions: "Открыть workflow в Actions",
    localCommand: "Или сгенерируйте локально:",
    tabDefault: "Repo Inspector · Статические отчеты",
    tabLoaded: "Repo Inspector · {repo} · {score}/100",
  },
};

const repoRegex = /^https?:\/\/github\.com\/([^/\s]+)\/([^/\s#]+?)(?:\.git)?\/?$/;
let lang = "en";

const refs = {
  title: document.getElementById("title"),
  subtitle: document.getElementById("subtitle"),
  labelRepo: document.getElementById("label-repo"),
  btnLoad: document.getElementById("btn-load"),
  form: document.getElementById("report-form"),
  message: document.getElementById("message"),
  help: document.getElementById("action-help"),
  reportRoot: document.getElementById("report-root"),
  langButtons: Array.from(document.querySelectorAll(".lang-btn")),
};

function t(key) {
  return I18N[lang][key];
}

function applyLanguage() {
  refs.title.textContent = t("title");
  refs.subtitle.textContent = t("subtitle");
  refs.labelRepo.textContent = t("repoLabel");
  refs.btnLoad.textContent = t("loadBtn");
  refs.langButtons.forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });
  document.title = t("tabDefault");
}

function parseRepoUrl(repoUrl) {
  const match = repoRegex.exec(repoUrl.trim());
  if (!match) return null;
  return { owner: match[1], repo: match[2] };
}

function currentRepoPath() {
  const host = window.location.hostname;
  const parts = window.location.pathname.split("/").filter(Boolean);
  if (host.endsWith(".github.io") && parts.length > 0) {
    const owner = host.replace(".github.io", "");
    const repo = parts[0];
    return { owner, repo };
  }
  return null;
}

function renderHelp(repoUrl) {
  const info = currentRepoPath();
  const actionUrl = info
    ? `https://github.com/${info.owner}/${info.repo}/actions/workflows/generate-report.yml`
    : "";

  const localCmd = `python scripts/generate_report.py --repo-url "${repoUrl}" --lang ${lang}`;
  const actionLink = actionUrl
    ? `<p><a href="${actionUrl}" target="_blank" rel="noopener">${t("openActions")}</a></p>`
    : "";
  refs.help.classList.remove("hidden");
  refs.help.innerHTML = `
    <p>${t("howToGenerate")}</p>
    ${actionLink}
    <p>${t("localCommand")}</p>
    <pre>${localCmd}</pre>
  `;
}

function renderReport(report) {
  const categories = report.categories || [];
  const metrics = report.project_metrics || {};
  refs.reportRoot.innerHTML = `
    <section class="card">
      <div class="score">
        <span>${t("totalScore")}</span>
        <span class="score-value">${report.score_total}/100</span>
      </div>
      <div class="score">
        <span>${t("codeLines")}</span>
        <span class="score-value">${metrics.total_code_lines || 0}</span>
      </div>
      <div class="score">
        <span>${t("codeFiles")}</span>
        <span class="score-value">${metrics.total_code_files || 0}</span>
      </div>
      ${categories.map(renderCategory).join("")}
    </section>
  `;
  const repoSlug = `${report.repo_owner || "owner"}/${report.repo_name || "repo"}`;
  document.title = t("tabLoaded")
    .replace("{repo}", repoSlug)
    .replace("{score}", String(report.score_total || 0));
}

function renderCategory(category) {
  const pct = category.weight ? Math.round((category.score / category.weight) * 100) : 0;
  const checksHtml = (category.checks || [])
    .map(
      (check) => `
        <div class="check">
          <span class="badge ${check.status}">${String(check.status).toUpperCase()}</span>
          <div>
            <div><strong>${check.name}</strong></div>
            <div class="muted">${check.details}</div>
          </div>
        </div>
      `
    )
    .join("");
  const recHtml =
    category.recommendations && category.recommendations.length
      ? `
        <div class="rec-title">${t("recommendations")}</div>
        <ul>${category.recommendations.map((item) => `<li>${item}</li>`).join("")}</ul>
      `
      : "";
  return `
    <article class="category">
      <div class="cat-head">
        <h3>${category.name}</h3>
        <strong>${category.score}/${category.weight}</strong>
      </div>
      <div class="bar"><div class="bar-fill" style="width:${pct}%"></div></div>
      ${checksHtml}
      ${recHtml}
    </article>
  `;
}

async function loadReport(repoUrl) {
  const parsed = parseRepoUrl(repoUrl);
  if (!parsed) {
    refs.message.textContent = t("invalidUrl");
    return;
  }
  refs.help.classList.add("hidden");
  refs.reportRoot.innerHTML = "";

  const fileName = `${parsed.owner}__${parsed.repo}.${lang}.json`;
  const response = await fetch(`./reports/${fileName}`, { cache: "no-store" });
  if (!response.ok) {
    refs.message.textContent = t("noReport");
    renderHelp(repoUrl);
    return;
  }
  const report = await response.json();
  refs.message.textContent = t("reportReady");
  renderReport(report);
}

refs.form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const repoUrl = String(new FormData(refs.form).get("repo_url") || "");
  await loadReport(repoUrl);
});

refs.langButtons.forEach((btn) => {
  btn.addEventListener("click", () => {
    lang = btn.dataset.lang || "en";
    applyLanguage();
  });
});

applyLanguage();

